### ISSUE TITLE
Nothing Wrong

### ISSUE THREAD

**Issue by Jafo232** [dobariyabhumika/arithmetic-calc#3]
I just wanted to thank you for this.  It saves me a lot of time on some math functionality I have in several projects.

I hope you revisit this package someday and and more functions to it. 💯

**Comment by dobariyabhumika** [comment]
@Jafo232  Thank You for your interest about this kind of package. I have started first time package development with this package.
You can suggest me for new function if you will need more functions in future.

**Comment by dobariyabhumika** [comment]
Sure in future I will revisit this package with new functions.
